import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import SmallCardContainer from './components/CardContainer/SmallCardContainer'
import CategoryBarContainer from './components/CategoryBar/CategoryBarContainer'
import Header from './components/Header'
import Location from './components/Location/Location'
import picture from '../data/pho/pho5.png'
const Home: NextPage = () => {

  const [selectedCategory, setSelectedCategory] = useState("breakfast")

  return (
    <div className={styles.container}>
      <Head>
        <title>Daily Donuts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <div className='w-full h-screen bg-[#1e283e] grid md:grid-cols-4 grid-cols-1'>
        {/* <video autoPlay loop muted style={{width:"100%"}}>
          <source src="/bgvideo.mp4" type='video/mp4'/>
        </video> */}
        <div className='col-span-1 md:col-span-2 flex flex-col justify-center items-center pt-[5rem] p-[2rem]'>
          <div className='text-[2rem] md:text[3rem] lg:text-[5rem] text-white '>Come Hungry. Leave Happy</div>
          <div className='text-[0.8rem] md:text-[1rem] text-white '>Cuisines are mirrors reflecting the culture and the history of each country. Italians are proud of their pizza; the Chinese are famous for their dumplings, Japanese love sushi... As for Vietnamese, we are well-known for our special Pho!</div>
        </div>
        <div className='col-span-1 md:col-span-2 flex items-center p-[2rem] bg-[#e7eaf2]'>
          <img className="w-full" src={picture.src}/>
        </div>
      </div>
      <CategoryBarContainer selectedCategory={selectedCategory} setSelectedCategory={setSelectedCategory}/>
      <SmallCardContainer selectedCategory={selectedCategory} />
      <Location/>

    </div>
  )
}

export default Home
