import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SmallCardContainer from './components/CardContainer/SmallCardContainer'
import Header from './components/Header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Deli Donu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <SmallCardContainer />
      {/* <Header/> */}

    </div>
  )
}

export default Home
